name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # go test
      - name: Go Test
        run: make
